
<link rel="stylesheet" type="text/css" href="/css/demo_table_jui.css">
<script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables-sorts.js"></script>
<script type="text/javascript" src="/js/liquidaciones/supplieroperations.js"></script>
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<style type="text/css">
    /*.ui-corner-all {
        position: static;
    }*/
    .chequesTotalShowTable {
        width:300px;
    }

    input.ui-button {
        vertical-align: bottom;
    }

</style>
<script type="text/javascript">
    $(document).ready(function(){
        $('.menu li:eq(7) a').addClass('current');
        $('.chkall').change(function(){
            if($(this).is(':checked')){
                $('[name="operation_chk"]').attr({'checked':'checked'});
                $('[name="rejected_chk"]').attr({'checked':'checked'});
            }else{
                $('[name="operation_chk"]').removeAttr('checked');
                $('[name="rejected_chk"]').removeAttr('checked');
            }
        });
    });

</script>

<div class="main">

    <form id="caveForm" action="<?php echo $this->url(array('module' => 'gyuser', 'controller' => 'liquidaciones', 'action' => 'supplieroperations'), null, true); ?>" method="post">

        <div style="margin-bottom:1em;">
            <h1 style="display:inline; font-size:20px">Proveedor </h1>
            <select name="cave_id" onchange="this.form.submit()" style="font-size:15px; vertical-align:bottom;" >
                <option value="" selected="selected">Seleccionar</option>
                <?php
                $cList = $this->cave;
                $opeArr = array();
                if (count($cList)) {
                    foreach ($cList as $cRow) {
                        echo "<option value='" . $cRow->getId() . "'>" . $cRow->getName() . "</option>";
                        $opeArr[$cRow->getId()] = $cRow->getName();
                    }
                }
                ?>
            </select>
            <input type="hidden" name="cave_selected_id" value="<?php if (isset($this->selectedCave)) echo $this->selectedCave; ?>" />
        </div>


        <!--
        <table class="table5p">
                <tr>
                        <td><h1>Seleccione colega</h1></td>
                        <td>
                                <select name="cave_id" >
                                        <option value="" selected="selected">Seleccionar</option>
        <?php /*
          $cList = $this->cave;
          $opeArr = array();
          if(count($cList)){
          foreach ($cList as $cRow){
          echo "<option value='".$cRow->getId()."'>".$cRow->getName()."</option>";
          $opeArr[$cRow->getId()] = $cRow->getName();
          }
          } */
        ?>
                                </select>
                                <input type="hidden" name="cave_selected_id" value="<?php //if(isset($this->selectedCave))echo $this->selectedCave;      ?>" />
                        </td>
                        <td>
                                <input type='button' value="GO" class="jqButton caveIdBtn" />
                        </td>
                </tr>
         </table>
        -->
       <!-- <h1>Cuenta corriente: <select name="cave_id" style="font:18px tahoma">
                                       <option value="" selected="selected">Seleccionar</option>
        <?php /*
          $cList = $this->cave;
          $opeArr = array();
          if(count($cList)){
          foreach ($cList as $cRow){
          echo "<option value='".$cRow->getId()."'>".$cRow->getName()."</option>";
          $opeArr[$cRow->getId()] = $cRow->getName();
          }
          } */
        ?>
                               </select><input type='button' value="GO" class="jqButton caveIdBtn" style="font-size:18px" /></h1>-->

    </form>
    <?php
    if (isset($this->caveFlag)) {

//the liquidaciones table will be outputted at the bottom of the page
        $liquidaciones_str = '';
        $liquidaciones_str = '

<h1>Liquidaciones Anteriores</h1>
<div style="width:50%">
<table cellpadding="0" cellspacing="0" border="0" class="display whiteTable" id="grid" width="700">
	<thead>
		<tr>
			<th width="30">Id</th>
			<th>Fecha</th>
			<th>Saldo</th>
			<th>Importe Pagado</th>
			<th width="100">&nbsp;</th>
		</tr>
	</thead>
	   <tbody class="gridtbody">';
        //<?php
        $supDet = $this->supList;
        $supBalance = @$supDet->getBalance();
        $supBalance = 0.00; //always reset.
        $pArr = $this->lqList;
        $strBld = "";
        $sName = "";
        $final_balance = NULL;
        $createNewLiquidaciones = true;
        if (count($pArr)) {
            foreach ($pArr as $pRow) {
                //$pRow	=	new Gyuser_Model_Liquidaciones();

                $final_balance = $pRow->getCurrent_account_balance();
                $Committed = (int) $pRow->getCommitted();
                if (!$Committed) {
                    $createNewLiquidaciones = false;
                    $redCls = 'redGridTr';
                } else {
                    $redCls = '';
                }


                $strBld .= <<<EOT
                            <tr id="liquidacionesid_{$pRow->getId()}" class="$redCls">
                                    <td class="user_id"> {$pRow->getId()} </td>
                                    <td class="">{$pRow->getDate()}</td>
                                    <td class="user_current_account_balance">{$this->amountFormat($final_balance)}</td>
                                    <td class="user_amount_payed">{$this->amountFormat($pRow->getAmount_payed())}</td>
                                    <td class="user_status">
                                            <ul id="icons">
                                                            <li class="viewBtn" title="View">
                                                                            <img src="/images/view_dark_icon.png" />
                                                                            <input type="hidden" value="{$Committed}" name="comitted"/>
                                                            </li>
                                                            <li class="pdfBtn" title="PDF"><img src="/images/pdf_icon.png" width="16" heigth="16" /></li>
                                                            <li class="excelBtn" title="Excel"><img src="/images/excel.png" /></li>
                                                            <li class="cancelBtn" title="Cancel"><img src="/images/cancel.png" /></li>
                                                            <li class="excelMailBtn" title="Mail Excel"><img src="/images/hd-form2excel.jpg" width="16" heigth="16" /></li>


                                            </ul>
                                    </td>
                            </tr>
EOT;
            }
        }

        //echo $strBld;
        $liquidaciones_str .= $strBld;
        $liquidaciones_str .= '
		</tbody>
	</table>
        </div>
<br/>';

        //if ($createNewLiquidaciones) {
            ?>
            <div id="LiquidacionesCreateBlock">
                <h1>Rechazos</h1>
                <table cellpadding="0" cellspacing="0" border="0" class="display whiteTable" id="operationGrid">
                    <thead>
                        <tr>
                            <th align="left""><input type='checkbox' class='chkall' checked='checked' /></th>
                            <th>Nombre</th>
                            <th>Fecha</th>
                            <th>N Cheque</th>
                            <th>Importe</th>
                            <th>Gastos</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody class="gridtbody">
                        <?php
                        $strBld = '';
                        $pay_final_amount = $final_balance * -1;
                        /*$pArr = $this->operationList;
                        
                        $supBalance = $supBalance * -1;
                        if ($supBalance) {
                            echo "<tr id='PreviousBalance'><td></td><td></td><td></td><td></td><td></td><td style='background:#E3E3E3;'>Balance</td><td  class='pay_amount_cls' style='background:#CCCCCC;'>{$this->amountFormat($supBalance)}</td></tr>";
                        } else {
                            echo "<tr id='PreviousBalance'><td></td><td></td><td></td><td></td><td></td><td style='background:#E3E3E3;'>Balance</td><td  class='pay_amount_cls' style='background:#CCCCCC;'>0.00</td></tr>";
                        }
                        //echo "<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>-</td></tr>";
                        if (count($pArr)) {
                            foreach ($pArr as $pRow) {
                                //$pRow	=	new Gyuser_Model_Operations();
                                $Other_caves_obj = $pRow->getOther_caves_obj();
                                $cavename = $Other_caves_obj->getName();
                                $User_obj = $pRow->getUser_obj();
                                $first_name = $User_obj->getFirst_name();
                                $last_name = $User_obj->getLast_name();
                                $total = $pRow->getAmount();
                                $halfamout = $total / 2;

                                $commision = 15;
                                $commisionAmount = $halfamout * $commision / 100;
                                $cave_pay = $halfamout - $commisionAmount;
                                $pay_final_amount += $cave_pay;
                                
                                $strBld .= <<<EOT
				<tr id="operationsid_{$pRow->getId()}">
					<td class="user_opr_chk"><input type="checkbox" name="operation_chk" checked="checked"/></td>
					<td class="user_amount">{$first_name} {$last_name}</td>
					<td class="user_amount">{$this->amountFormat($total)}</td>
					<td class="user_amount">{$this->amountFormat($halfamout)}</td>
					<td class="user_amount"> - {$this->amountFormat($commisionAmount)}</td>
					<td class="user_amount"></td>
					<td class="user_amount"></td>
					<td class="user_amount"></td>
					<td class="pay_amount_cls">{$this->amountFormat($cave_pay)}</td>
				</tr>
EOT;
                            }
                        }
                        echo $strBld;
*/
                        $pArr = $this->rejectedCheques;
                        $strBld = '';
                        $sName = '';
                        
                        if (count($pArr)) {
                            foreach ($pArr as $pRow) {
                                //$pRow	=	new Gyuser_Model_Cheques();
                                $Clients_obj = $pRow->getClients_obj();
                                $Cheques_status_obj = $pRow->getCheques_status_obj();
                                $Bank_accounts_obj = $pRow->getBank_accounts_obj();
                                //$rejectedChequesFee = (int) $pRow->getRejected_gastos();
                                $cMapper = new Gyuser_Model_ChequesDataMapper ();
                                $rejectedChequesFee = (int) $cMapper->GetRejectionCost($pRow);
                                $amount = $pRow->getAmount();
                                $rChequeWithFee = $amount + $rejectedChequesFee;
                                $pay_final_amount += $rChequeWithFee;

                                $strBld .= <<<EOT
				<tr id="RejectedCheque_{$pRow->getId()}" style="background:#E3E3E3;">
					<td class="user_rej_chk"><input type="checkbox" name="rejected_chk" checked="checked"/></td>
					<td class="user_operation_id">{$Clients_obj->getFirst_name()} {$Clients_obj->getLast_name()}<input type="hidden" value="{$pRow->getOperation_id()}" name="operation_id"/></td>
                                        				
                                        <td class="user_date">{$pRow->getDate()}</td>
					<td class="user_check_n">{$pRow->getCheck_n()}</td>					
					<td class="user_amount">{$this->amountFormat($amount)}</td>
					<td class="user_rejected_cheque_fee">{$this->amountFormat($rejectedChequesFee)}</td>
					
					<td class="pay_amount_cls">{$this->amountFormat($rChequeWithFee)}</td>
				</tr>
EOT;
                            }
                        }
                        echo $strBld;

                        echo '<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>';
                        echo "<tr id='Acreditacion'><td></td><td></td><td></td><td></td><td></td><td>Acreditaci&oacute;n</td><td><input type='text' name='acreditacion' class='pay_amount_cls' /></td></tr>";
                        echo "<tr><td></td><td></td><td></td><td></td><td></td><td style='background:#E3E3E3;border-right-color:#ccc'>SALDO A LIQUIDAR</td><td style='background:#e3e3e3;'><span class='pay_final_amount_span'>{$this->amountFormat($pay_final_amount)}</span><input type='hidden' id='pay_final_amount' value='$pay_final_amount' /></td></tr>";
                        
                        ?>

                    </tbody>
                </table>
                <br/>
                <?php
                    $html_tasaAnual = '';
                    $html_tasaDiaria = '';
                    if (@$supDet) {
                        $html_tasaAnual = $supDet->getTasa_anual();
                        $html_tasaDiaria = round($supDet->getTasa_anual() / 360, 3);
                    }                        
                ?>

                <h1>C&aacute;lculo de Descuento  <span style="font-size:15px"> - Tasa Anual <span class=""><?=$html_tasaAnual?></span>% (<?=$html_tasaDiaria?>%)</span> <input type='button' class='chooseChequesBtn jqButton' value='Seleccionar Cheques'/> <br />
                    <span style="font-size:15px">Fecha de Liquidaci&oacute;n:</span> <input size="10" type="text" class="datepicker currentDateLiq" />
                </h1>

                <table cellpadding="0" cellspacing="0" border="0" class="display whiteTable" id="viewChequesGrid">
                    <thead>
                        <tr>
                            <th>Titular</th>
                            <th>Empresa</th>
                            <th>N. Cheque</th>
                            <th>Locacion</th>
                            <th>Plazo</th>
                            <th>Fecha Dep.</th>
                            <th>Fecha Acred.</th>
                            <th>Dias</th>                            
                            <th>Importe</th>
                        </tr>
                    </thead>
                    <tbody class="gridtbody">


                    </tbody>
                </table>


                <div class="chequeList" title="Libro de cheques (<?php echo count($this->cList) ?>)">

                    <fieldset>
                        <form action="" method="post" id="AddProductSizeForm">
                            <table class="table5p whiteTable" align="center">
                                <tr>
                                    <td>
                                        <table cellpadding="0" cellspacing="0" border="0" class="table5p" id="chequesGrid" style="min-width:700px">
                                            <thead>
                                                <tr>
                                                    <th><!-- <input type="checkbox" class="raw_select_all" /> --></th>
                                                    <th>Id</th>
                                                    <th>Titular</th>
                                                    <th>Empresa</th>
                                                    <th>Fecha</th>
                                                    <th>N. Cheque</th>                                                    
                                                    <th>Importe</th>
                                                    <th>Valor al Dia</th>
                                                </tr>
                                            </thead>
                                            <tbody class="gridtbody">

                                            </tbody>
                                        </table>

                                    </td>
                                </tr>


                            </table>

                        </form>
                    </fieldset>
                    <div  class="ui-widget-header ui-corner-all chequesTotalShowTable">
                        <table class="table5p">
                            <tr>
                                <td class="result-panel-td">CANTIDAD DE CHEQUES</td>
                                <td class="result-panel-td"> : </td>
                                <td class="result-panel-td"> <span class="qtyCls">0.00</span></td>
                            </tr>
                            <tr>
                                <td class="result-panel-td">IMPORTE A LIQUIDAR </td>
                                <td class="result-panel-td"> : </td>
                                <td class="result-panel-td"> <span class="payCls">0.00</span></td>
                            </tr>
                            <tr>
                                <td class="result-panel-td">IMPORTE EN CHEQUES </td>
                                <td class="result-panel-td"> : </td>
                                <td class="result-panel-td"> <span class="payingCls">0.00</span></td>
                            </tr>
                            <tr>
                                <td class="result-panel-td">SALDO</td>
                                <td class="result-panel-td"> : </td>
                                <td class="result-panel-td"> <span class="balanceCls">0.00</span></td>
                            </tr>
                        </table>
                    </div>


                </div>
                <br/>
                <div>
                    <div class="finalPayView ui-corner-all ui-dialog  ui-dialog-titlebar ui-widget-header liqDetailsBox">
                        <table class="table5p">
                            <tr>
                                <td>IMPORTE A LIQUIDAR </td>
                                <td> : </td>
                                <td> <span class="payCls">0.00</span></td>
                            </tr>
                            <tr>
                                <td>IMPORTE EN CHEQUES </td>
                                <td> : </td>
                                <td> <span class="payingCls">0.00</span></td>
                            </tr>
                            <tr>
                                <td>SALDO PENDIENTE </td>
                                <td> : </td>
                                <td> <span class="balanceCls">0.00</span></td>
                            </tr>                           
                        </table>
                    </div>
                   
                    <table style="margin-top:.5em;">
                        <tr>
                            <td colspan="3" align="right"><input type="button" value="Crear Liquidaci&oacute;n" class="sendCheques jqButton"  /></td>
                        </tr>
                    </table>
                </div>



                <form id="PayChecksForm" action="<?php echo $this->url(array('module' => 'gyuser', 'controller' => 'liquidaciones', 'action' => 'liquidacionespaysuppliercheques'), null, true); ?>" method="post" >
                    <input type="hidden" value="" name="date"/>
                    <input type="hidden" value="" name="current_account_balance"/>
                    <input type="hidden" value="" name="amount_payed"/>
                    <input type="hidden" value="" name="cheques_json" />
                    <input type="hidden" value="" name="operations_json" />
                    <input type="hidden" value="" name="rejected_cheques_json" />
                    <input type="hidden" value="" name="previous_account_balance"/>
                    <input type="hidden" value="" name="acreditacion"/>
                    <input type="hidden" value="" name="pay_final_amount_edit"/>

                    <input type="hidden" value="" name="checks_qty"/>
                    <input type="hidden" value="" name="average_days"/>
                    <input type="hidden" value="" name="total_bruto"/>
                    <input type="hidden" value="" name="impuesto_al_cheque_amt"/>
                    <input type="hidden" value="" name="intereses"/>
                    <input type="hidden" value="" name="gastos_interior"/>
                    <input type="hidden" value="" name="gastos_general"/>
                    <input type="hidden" value="" name="gastos_varios"/>
                    <input type="hidden" value="" name="total_neto"/>
                    <input type="hidden" name="cave_id" value="<?php if (isset($this->selectedCave)) echo $this->selectedCave; ?>" />
                </form>
                <br/><br/>
                <hr />
            </div>



            <?php
        //}else {
        //    echo '<p><strong>Liquidaci&oacute;n pendiente.</strong> Por favor, consolide la liquidaci&oacute;n actual antes de iniciar una nueva.</p>';
        //}
        echo $liquidaciones_str;
        ?>
        <div class="chequeListByLiquidacionesId" title="Detalle de Liquidaci&oacute;n">


            <h1 class="loadOperations">Cargando...</h1>
            <h1 style="margin-top:0">Rechazos y Gastos</h1>
            <table cellpadding="0" cellspacing="0" border="0" class="display whiteTable" id="operationGridByLiquidacionesId">
                <thead>
                    <tr>
                        <th></th>
                        <th>Nombre</th>
                        <th>Fecha</th>
                        <th>N Cheque</th>
                        <th>Importe</th>
                        <th>Gastos</th>
                        <th>Saldo</th>
                    </tr>
                </thead>
                <tbody class="gridtbody">
                </tbody>
            </table>
            <h1>Cheques</h1>
            <table  cellpadding="0" cellspacing="0" border="0" class="display whiteTable"  id="chequesGridByLiquidacionesId">
                <thead>
                    <tr>
                        <th class="chkInpckb" ></th>
                        <th>Titular</th>
                        <th>Banco</th>
                        <th>N. Cheque</th>
                        <th>Locacion</th>
                        <th>Plazo</th>
                        <th>Fecha Dep.</th>
                        <th>Fecha Acred.</th>
                        <th>D&iacute;as</th>                        
                        <th>Importe</th>
                    </tr>
                </thead>
                <tbody class="gridtbody">
                </tbody>
            </table>
            <h2>Detalle</h2>
            <table  cellpadding="0" cellspacing="0" border="0" class="display whiteTable"  id="chequesDetailsByLiquidacionesId">
                <thead>
                    <tr>
                        <th>Cant. Cheques</th>
                        <th>D&iacute;as Promedio</th>
                        <th>Bruto</th>
                        <th>Impuesto al Cheque</th>
                        <th>Intereses</th>                        
                        <th>Gs. Grales</th>
                        <th>Gs. Interior</th>
                        <th>Gs. Otros</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody class="gridtbody">
                </tbody>
            </table>
            <br/>
            <div class="finalPayViewByLiquidacionesId ui-corner-all ui-dialog  ui-dialog-titlebar ui-widget-header">
                <table class="table5p">
                    <tr>
                        <td>IMPORTE A LIQUIDAR </td>
                        <td> : </td>
                        <td> <span class="payCls">0.00</span></td>
                    </tr>
                    <tr>
                        <td>IMPORTE EN CHEQUES </td>
                        <td> : </td>
                        <td> <span class="payingCls">0.00</span></td>
                    </tr>
                    <tr>
                        <td>SALDO</td>
                        <td> : </td>
                        <td> <span class="balanceCls">0.00</span></td>
                    </tr>
                </table>
            </div>


            <form id="PayChecksEditForm" style="display:none;" action="<?php echo $this->url(array('module' => 'gyuser', 'controller' => 'liquidaciones', 'action' => 'editliquidacionespaychequessupplier'), null, true); ?>" method="post" >
                <input type="hidden" value="" name="id"/>
                <input type="hidden" value="" name="date"/>
                <input type="hidden" value="" name="current_account_balance"/>
                <input type="hidden" value="" name="amount_payed"/>
                <input type="hidden" value="" name="previous_account_balance"/>
                <input type="hidden" value="" name="cheques_json" />
                <input type="hidden" value="" name="operations_json" />
                <input type="hidden" value="" name="rejected_cheques_json" />
                <input type="hidden" value="1" name="committed" />
                <input type="hidden" value="" name="acreditacion"/>

                <input type="hidden" value="" name="checks_qty"/>
                <input type="hidden" value="" name="average_days"/>
                <input type="hidden" value="" name="total_bruto"/>
                <input type="hidden" value="" name="impuesto_al_cheque_amt"/>
                <input type="hidden" value="" name="intereses"/>
                <input type="hidden" value="" name="gastos_interior"/>
                <input type="hidden" value="" name="gastos_general"/>
                <input type="hidden" value="" name="gastos_varios"/>
                <input type="hidden" value="" name="total_neto"/>
                <input type="hidden" name="cave_id" value="<?php if (isset($this->selectedCave)) echo $this->selectedCave; ?>" />
            </form>
        </div>


    <?php } ?>
    <div class="ui-dialog mainMsgDiv" >
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix mainMsgInnerDiv">
            <span class="ui-dialog-title" id="mainMsg">
                Editar Usuario
            </span>
            <a href="#" class="ui-dialog-titlebar-close ui-corner-all msgClose" role="button">
                <span class="ui-icon ui-icon-closethick">Cerrar</span></a>
        </div>
    </div>
    <select id="stateDrp" style="display:none;">
        <option value="">Seleccionar</option>
        <option value="24">Buenos Aires</option><option selected="selected" value="1">Capital</option><option value="4">Catamarca</option><option value="19">Chaco</option><option value="10">Chubut</option><option value="13">C&oacute;rdoba</option><option value="3">Corrientes</option><option value="18">Formosa</option><option value="8">Jujuy</option><option value="22">La Pampa</option><option value="20">La Rioja</option><option value="14">Mendoza</option><option value="9">Misiones</option><option value="17">Neuqu&eacute;n</option><option value="11">Rio Negro</option><option value="6">Salta</option><option value="15">San Juan</option><option value="21">San Luis</option><option value="23">Santa Cruz</option><option value="2">Santa Fe</option><option value="5">Santiago del Estero</option><option value="12">Tierra del Fuego</option><option value="7">Tucum&aacute;n</option></select>

    <?php
    if (@$supDet) {
        echo "
        <input type='hidden' class='impuesto_al_cheque' value='{$supDet->getImpuesto_al_cheque()}' />
        <input type='hidden' class='tasa_anual' value='{$supDet->getTasa_anual()}' />
        <input type='hidden' class='gastos_general' value='{$supDet->getGastos_general()}' />
        <input type='hidden' class='gastos_interior' value='{$supDet->getGastos_interior()}' />
        <input type='hidden' class='acreditacion_capital' value='{$supDet->getAcreditacion_capital()}' />
        <input type='hidden' class='acreditacion_interior' value='{$supDet->getAcreditacion_interior()}' />

        <input type='hidden' class='gastos_cheque_menor_a_1' value='{$supDet->getGastos_cheque_menor_a_1()}' />
        <input type='hidden' class='gastos_cheque_a_1' value='{$supDet->getGastos_cheque_a_1()}' />
        <input type='hidden' class='gastos_cheque_menor_a_2' value='{$supDet->getGastos_cheque_menor_a_2()}' />
        <input type='hidden' class='gastos_cheque_a_2' value='{$supDet->getGastos_cheque_a_2()}' />
";
    }
    ?>
    <input type="hidden" id="ServerCurrentDate" value="<?php echo $this->currentDate; ?>" />